# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Configuration file for build in doc/ subdirectory
sphinx:
  configuration: doc/conf.py

# Specify mambaforge such that we can install dependencies via mamba package manager
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    install:
      - tar --exclude=./python -cvf ./python/s-dftd3.tar . && mkdir -p ./python/subprojects/s-dftd3 && tar xvf ./python/s-dftd3.tar -C ./python/subprojects/s-dftd3
      - pip install ./python -v

# Get dependencies for docs, package and build from conda-forge
conda:
  environment: doc/environment.yml
