set(CMAKE_IMPORT_FILE_VERSION 1)

set(
  SDFTD3_INCLUDEDIRS
  "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@"
  "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@/@module-dir@"
)
find_library(
  SDFTD3_LIBRARIES
  "@PROJECT_NAME@"
  PATHS "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@"
  NO_DEFAULT_PATH
)
set(
  SDFTD3_DEPENDENCIES
  "$<$<BOOL:${SDFTD3_USE_MCTCLIB}>:mctc-lib::mctc-lib>"
  "$<$<BOOL:${SDFTD3_WITH_OpenMP}>:OpenMP::OpenMP_Fortran>"
)

add_library(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE IMPORTED)
add_library(@PROJECT_NAME@::@PROJECT_NAME@ ALIAS @PROJECT_NAME@::@PROJECT_NAME@-lib)
target_link_libraries(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE ${SDFTD3_LIBRARIES} ${SDFTD3_DEPENDENCIES})
target_include_directories(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE ${SDFTD3_INCLUDEDIRS})
