name: Fortran CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build with meson and ninja
      run: |
        docker pull jpakkane/mesonci
        meson setup build_gcc
        ninja -C build_gcc test
